dBildungsplattform/dbildungs-iam-server

sonar-project.properties

This pull request fixes the bug of false positives on sonarcloud. Report of coverage will be excluded form the analysis of the code.
Ticket: https://ticketsystem.dbildungscloud.de/browse/EW-574
reduce the finding of false positives at the sonarcloud project of dbildungs-iam-server.
> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

EW-574 exclude report of coverage from sonarcloud analysis

---

.github/workflows/push.yml
sonar-project.properties

Deactivates trigger of SonarCloud analysis due to missing licenses for SonarCloud instance for this github organization. 
https://ticketsystem.dbildungscloud.de/browse/EW-600

EW-600 Temporarily deactivate SonarCloud job on pull request

---

.github/workflows/push.yml
sonar-project.properties

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

Reenabled SonarCloud

---

.github/workflows/on_push_or_pr.yml

OPS-5191 Added comment wo workflow

---

src/modules/keycloak-administration/domain/keycloak-user.service.spec.ts
src/modules/keycloak-administration/domain/keycloak-user.service.ts
src/modules/keycloak-administration/index.ts
src/modules/person/api/create-person.body.params.spec.ts
src/modules/person/api/create-person.body.params.ts
src/modules/person/api/person-api.mapper.profile.spec.ts
src/modules/person/api/person-api.mapper.profile.ts
src/modules/person/api/person.controller.spec.ts
src/modules/person/api/person.uc.spec.ts
src/modules/person/api/person.uc.ts
src/modules/person/domain/create-person.dto.ts
src/modules/person/domain/person.do.ts
src/modules/person/domain/person.service.spec.ts
src/modules/person/persistence/person.entity.ts
src/modules/person/person-api.module.ts
src/server/server.module.ts
test/utils/do-factory.ts

When creating a person a keycloak user will also be created and linked to that person.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-40

SPSH-40 Create Keycloak user when creating person

---

.github/workflows/reusable_job_nest_test_sonarcloud.yml
README.md
config/config.dev.json
config/config.prod.json
config/config.test.json
docs/config.md
package-lock.json
package.json
src/frontend/frontend.module.ts
src/modules/frontend/api/frontend.controller.spec.ts
src/modules/frontend/api/frontend.controller.ts
src/modules/keycloak-administration/domain/keycloak-admin-client.service.ts
src/shared/config/config.loader.spec.ts
src/shared/config/keycloak.config.ts

This PR adds nest-keycloak-connect which enables verification of users using the authorization header.
To manually test this feature:
1. Create a (or reuse an existing) client in keycloak
2. Make sure the client has "Client authentication" enabled has permission "direct access grants" (getting token on user behalf)
3. Get secret token from "credentials" tab and update server config
4. Request token on behalf of user 
```sh
curl  -X POST \
'http://127.0.0.1:8080/realms/{{your-realm}}/protocol/openid-connect/token' \
--header 'Accept: */*' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'scope=openid' \
--data-urlencode 'username={{username}}' \
--data-urlencode 'password={{password}}' \
--data-urlencode …
```

SPSH-89 Keycloak Guards

---

.github/workflows/on_push_or_pr.yml

OPS-5273 workflow runs on every sub branch

---

config/config.dev.json
config/config.prod.json
config/config.test.json
src/console/console.module.ts
src/server/server.module.ts
src/shared/config/config.loader.spec.ts
src/shared/config/db.config.ts

We need to configure whether or not to connect to the DB using an ssl connection

Added ssl-param for db connection

---

.github/workflows/reusable_job_nest_test_sonarcloud.yml
README.md
compose.yaml
config/config.dev.json
config/config.test.json
dev-realm-spsh.json
docs/auth.md
docs/config.md
src/modules/health/health.controller.spec.ts
src/modules/person/api/person.controller.ts
src/modules/ui-backend/domain/login.service.ts
src/server/server.module.ts
src/shared/config/config.loader.spec.ts
src/shared/config/keycloak.config.ts

This PR adds keycloak with a default development realm to the `compose.yml`.
Also adds correct configuration to the `config.dev.json` (The secrets are public knowledge and saved in the development-realm)
The realm will only be imported, if it doesn't exist. To reset the realm simply recreate the container (Or delete the realm in the keycloak UI and restart the container)
For developers: You can annotate your endpoints/controllers with `@Public()` or `@Unprotected()` (Both do the same) to opt out of authorization.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-127

SPSH-127 default developer keycloak and docs

---

src/server/server.module.ts

Remove the resource guard, since it isn't needed and it pollutes the logs.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-126

SPSH-126 Remove resource guard

---

.github/workflows/image-publish-on-push-to-branch.yml
.github/workflows/image-publish-on-push-to-main.yml

Run sonarcloud scan on the main branch, too.

DBP-332-sonarcloud

---

config/config.dev.json
dev-realm-spsh.json
src/modules/frontend/api/frontend.controller.spec.ts
src/modules/frontend/api/frontend.controller.ts
src/modules/frontend/auth/authenticated.guard.spec.ts
src/modules/frontend/auth/authenticated.guard.ts
src/modules/frontend/frontend-api.module.ts
src/modules/frontend/outbound/provider.service.spec.ts
src/modules/frontend/outbound/provider.service.ts

Some small changes needed for login/logout in the client
- https://ticketsystem.dbildungscloud.de/browse/SPSH-143
- https://github.com/dBildungsplattform/schulportal-client/pull/16
Should be merged in conjunction with client

SPSH-143 Make changes needed for frontend login

---

config/config.dev.json
docs/config.md
src/backend-for-frontend/main.ts
src/shared/config/frontend.config.ts
src/shared/util/one-of.validator.decorator.spec.ts
src/shared/util/one-of.validator.decorator.ts

Adds the ability to configure express' "trust proxy" settings for BFF.
See https://expressjs.com/en/guide/behind-proxies.html for a guide.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-152

SPSH-152 Add TRUST_PROXY config for BFF

---

.github/workflows/image-publish-check-on-push-scheduled.yml

Use hash instead of (not-existing) Ticket as image tag for dependabot.
[DBP-354](https://ticketsystem.dbildungscloud.de/browse/DBP-354)

DBP-354-handle-image-tag-for-dependabot

---

Dockerfile

Updated Dockerfile to new node and alpine version as well as libssl3 and libcrypto versions to fix trivy-warnings

Pull up node and alpine version as well as libraries

---

src/modules/user/user.module.spec.ts
src/modules/user/user.module.ts
src/modules/user/user.repository.ts
src/modules/user/username-generator.service.integration-spec.ts
src/modules/user/username-generator.service.spec.ts
src/modules/user/username-generator.service.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-158
Introduces a UserModule and gives it a method to generate a user name.

Spsh 158 derrive username

---

charts/dbildungs-iam/templates/dbildungs-iam-deployment-backend.yaml
charts/dbildungs-iam/templates/dbildungs-iam-deployment-bff.yaml
charts/dbildungs-iam/templates/redis-deployment.yaml
charts/dbildungs-iam/values.yaml

Add initial CPU/RAM requests (otherwise the limit is used and prevents scheduling of the pods).
Removed hostPort that prevented scheduling of multiple instances,
[DBP-374](https://ticketsystem.dbildungscloud.de/browse/DBP-374)
[DBP-390](https://ticketsystem.dbildungscloud.de/browse/DBP-390)

DBP-390-add-requests

---

charts/dbildungs-iam/charts/dbildungs-iam-keycloak-dev/dev-realm-spsh.json
charts/dbildungs-iam/values.yaml

The Configuration data from which KC was set up was missing important parameters.
* Client Secret
* Root URL

Spsh 224 fix realm export

---

src/modules/organisation/api/create-organisation.body.params.ts
src/modules/organisation/api/create-organisation.dto.ts
src/modules/organisation/api/created-organisation.dto.ts
src/modules/organisation/api/find-organisation-query.param.ts
src/modules/organisation/api/find-organisation.dto.ts
src/modules/organisation/api/organisation-api.mapper.profile.spec.ts
src/modules/organisation/api/organisation-api.mapper.profile.ts
src/modules/organisation/api/organisation.controller.spec.ts
src/modules/organisation/api/organisation.response.ts
src/modules/organisation/api/organisation.uc.spec.ts
src/modules/organisation/domain/organisation.do.ts
src/modules/organisation/domain/organisation.enums.ts
src/modules/organisation/persistence/organisation.entity.ts
src/modules/organisation/persistence/organisation.scope.ts
test/utils/do-factory.ts

- Add trägerschaft to organization.
**Changed database schema**
https://ticketsystem.dbildungscloud.de/browse/EW-669

EW-669: Add traegerschaft to organization.

---

.github/workflows/chart-release-manual.yml

DBP-0000 Corrected GHA parameter name

---

src/modules/frontend/api/frontend.controller.spec.ts
src/modules/frontend/outbound/person.service.spec.ts
src/modules/person/api/create-person.body.params.spec.ts
src/modules/person/api/create-person.body.params.ts
src/modules/person/api/person-api.mapper.profile.spec.ts
src/modules/person/api/person-api.mapper.profile.ts
src/modules/person/api/person.controller.spec.ts
src/modules/person/api/person.controller.ts
src/shared/validation/global-validation.pipe.spec.ts

Removes the unnecessary username field from the CreatePerson endpoint.

SPSH-311 Remove username field from create person

---

.github/workflows/chart-release-manual.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
charts/dbildungs-iam/templates/dbildungs-iam-deployment-backend.yaml

- use the version 5 so appversion is properly cut, this makes it so that image in Cluster reference is fixed, Code has been fixed, just not updated in this repo

DBP-559-test-rollout-of-helm-charts

---

compose.yaml

Adjust docker-compose to wait for startup on necessary compontent (redis, db, keycloak)
- https://ticketsystem.dbildungscloud.de/browse/SPSH-361

SPSH-361: Fix Docker Compose

---

charts/dbildungs-iam/config/config.json
charts/dbildungs-iam/templates/_dbildungs-iam-envs.tpl
charts/dbildungs-iam/templates/dbildungs-iam-configmap.yaml
charts/dbildungs-iam/templates/dbildungs-iam-deployment-backend.yaml
charts/dbildungs-iam/values.yaml
src/shared/config/config.env.ts
src/shared/config/config.loader.spec.ts
src/shared/config/config.loader.ts

Make the server run on Kubernetes by extracting configuration parameters and constructing URLs

Spsh 347 adjust keycloak parameters

---

src/modules/rolle/api/rolle.controller.integration-spec.ts
src/modules/rolle/api/rolle.controller.ts
src/modules/rolle/repo/rolle.repo.spec.ts
src/modules/rolle/repo/rolle.repo.ts
test/utils/do-factory.ts

SPSH-358 Add endpoint to list all rollen

---

charts/dbildungs-iam/config/config.json
charts/dbildungs-iam/seeding/dev/01_organisation.json

Add seed-data and config for root organisation to charts

SPSH-404 Fix config and seed data

---

charts/dbildungs-iam/templates/dbildungs-iam-seeding-dev-configmap.yaml
sql/dev/00_data-provider.json
sql/dev/01_organisation.json
sql/dev/02_person.json
sql/dev/04_rolle.json
src/console/db-init.console.ts
src/console/dbseed/db-seed.console.ts
src/console/main.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-426

Spsh 426, Seeding and Init use proper return values. Seeding files are now no longer hard coded in config

---

charts/dbildungs-iam/templates/dbildungs-iam-ingress.yaml

Enpoints to get auto generated JSON and YAML are now publicly available
- https://ticketsystem.dbildungscloud.de/browse/SPSH-421

Added auto-generated doc endpoints to ingress

---

src/modules/rolle/api/rolle.controller.ts

the GET rollen endpoint was missing a return type.

SPSH-436 Add API definition for GET rollen

---

src/modules/organisation/api/organisation.controller.ts
src/modules/person/api/person.controller.ts

Added return value specs to API, those were preventing automatic generation of API clients
https://ticketsystem.dbildungscloud.de/browse/SPSH-430

Added return value specs to API

---

charts/dbildungs-iam/templates/dbildungs-iam-deployment-backend.yaml
charts/dbildungs-iam/values.yaml

Set the pull policy

---

src/modules/person/api/person.uc.spec.ts
src/modules/person/api/person.uc.ts
src/modules/person/domain/person.spec.ts
src/modules/person/domain/person.ts
src/shared/util/result-interceptor.spec.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-451

Spsh 451, Fix password reset

---

src/modules/organisation/api/organisation.controller.ts

SPSH-369 Add missing return type

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
charts/dbildungs-iam/templates/_dbildungs-iam-envs.tpl
charts/dbildungs-iam/templates/dbildungs-iam-deployment-backend.yaml
charts/dbildungs-iam/templates/secret.yaml
charts/dbildungs-iam/values.yaml

Dbp 547 configure and separate configs and secrets

---

.github/dependabot.yml

add eslint group for dependapot

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-623 Cross branch deployment

---

src/modules/person/api/person.response.ts

Adds API decorators to person response

SPSH-490 Add API decorators to person response

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-696 Make deploy inherit secrets

---

Dockerfile
package-lock.json
package.json

Made the node version be more explicit, so that there will not be spurious updates due to the patchlevel changing.
Made the application depend on exaktly that version

Fixed Node Version

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

Dbp 706 fix issues when image upload fails

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
charts/dbildungs-iam-server/values.yaml

DBP-647-small-improvements-fix

---

src/modules/service-provider/api/provider.controller.ts

Renamed one method in controller for service-providers.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-528

SPSH-528 renamed method all service-providers

---

jest.config.cjs

Coverage report is currently inconsistent and prevents us from working. This PR reduces the coverage requirements to 90% until the problem is fixed.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-587

SPSH-587 Decrease coverage requirements

---

src/modules/personenkontext/api/find-schulstrukturknoten.response.ts

SPSH-579 Fix typo

---

src/modules/person/api/person.controller.ts

EW-826 attribute mapping correction by create person

---

charts/dbildungs-iam-server/seeding/dev/02_person.json
seeding/dev/02_person.json

Seeding data modified.
https://ticketsystem.dbildungscloud.de/browse/SPSH-634

Fixed seedingsdaten

---

src/modules/person/api/person.frontend.controller.ts
src/modules/person/api/personen-query.param.ts
src/modules/personenkontext/api/dbiam-personenkontext-filter.controller.ts
src/modules/personenkontext/api/find-personenkontext-schulstrukturknoten.body.params.ts

Search strings are now optional but can also handle an empty string.
https://ticketsystem.dbildungscloud.de/browse/SPSH-644

SPSH-644-suchstring-optional

---

src/modules/person/api/personenuebersicht/dbiam-personenzuordnung.response.ts

Added new field "administriertVon" to the response in order to find out which Schule is responsible for which Klasse.
https://ticketsystem.dbildungscloud.de/browse/SPSH-617

SPSH-617-klasse-overview

---

charts/dbildungs-iam-server/seeding/dev/02_person.json
charts/dbildungs-iam-server/seeding/dev/05_personenkontext.json
seeding/dev/01/02_person.json
seeding/dev/01/05_personenkontext.json

More seeding data for testing epics.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-682

SPSH-682: Mehr Seeding Daten

---

docs/event-bus.md

https://ticketsystem.dbildungscloud.de/browse/SPSH-726

Added architectural considerations about event-usage

---

src/modules/rolle/api/rolle-name-query.param.ts
src/modules/rolle/api/rolle.controller.integration-spec.ts
src/modules/rolle/api/rolle.controller.ts
src/modules/rolle/repo/rolle.repo.ts

Adjust GET /api/rolle to return paged response and accept limit and offset parameter.
- https://ticketsystem.dbildungscloud.de/browse/SPSH-729

SPSH-729: PagedResponse for Rolle

---

charts/dbildungs-iam-server/seeding/dev/01_organisation.json
charts/dbildungs-iam-server/seeding/dev/02_person.json
seeding/dev/01/01_organisation.json
seeding/dev/01/02_person.json

Sets fixed usernames for all test-users

SPSH-776 set fixed usernames for seeding

---

src/modules/person/person-api.module.ts
src/modules/rolle/rolle.module.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-818

remove unnecessary providers

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

- update Dev Pipeline to Version 5 so that the Ldap Server gets rolled out too

DBP-799-openldap-image-helm-chart

---

.github/workflows/create-release.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

the default time out is after 10 minutes, with this we set the value to 15 minutes

OPS-0000-increase-timeout-of-tests

---

charts/dbildungs-iam-server/migrations/Migration20240722092146.js

SPSH-927: Add latest migration for in-cluster usage

---

package-lock.json
src/modules/organisation/persistence/organisation.repository.ts
src/modules/rolle/api/rolle.controller.integration-spec.ts
src/modules/rolle/api/rolle.controller.ts
src/modules/rolle/repo/rolle.repo.spec.ts
src/modules/rolle/repo/rolle.repo.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-922

SPSH 922, Paging für Rollen

---

src/core/ldap/domain/ldap-client.service.spec.ts
src/core/ldap/domain/ldap-client.service.ts
src/core/ldap/domain/ldap-event-handler.spec.ts
src/core/ldap/domain/ldap-event-handler.ts
src/modules/itslearning/event-handlers/itslearning-organisations.event-handler.spec.ts
src/modules/itslearning/event-handlers/itslearning-organisations.event-handler.ts
src/modules/organisation/domain/organisation.enums.ts
src/modules/organisation/persistence/organisation.repo.ts
src/modules/organisation/persistence/organisation.repository.integration-spec.ts
src/modules/organisation/persistence/organisation.repository.ts
src/shared/events/schule-created.event.ts
src/shared/events/schule-deleted.event.ts

- Extdended the parameters for the  Organisations-Events 
- Refactored the events: SchuleCreatedEvent and SchuleDeletedEvent and the event handlers: ItsLearningOrganisationsEventHandler, LdapEventHandler
- Moved the method findParentId from the ItsLearningOrganisationsEventHandler into the organisation repository
- Unit-tests and integration tests.
https://ticketsystem.dbildungscloud.de/browse/SPSH-843

SPSH-843: Organisations-Events erweitern & Refactoring

---

src/core/ldap/domain/ldap-event-handler.spec.ts
src/modules/itslearning/actions/base-mass-action.spec.ts
src/modules/itslearning/actions/base-mass-action.ts
src/modules/itslearning/actions/create-group.action.ts
src/modules/itslearning/actions/create-memberships.action.spec.ts
src/modules/itslearning/actions/create-memberships.action.ts
src/modules/itslearning/actions/create-person.action.spec.ts
src/modules/itslearning/actions/create-person.action.ts
src/modules/itslearning/actions/delete-memberships.action.spec.ts
src/modules/itslearning/actions/delete-memberships.action.ts
src/modules/itslearning/actions/read-all-persons.action.ts
src/modules/itslearning/actions/read-person.action.spec.ts
src/modules/itslearning/actions/read-person.action.ts
src/modules/itslearning/event-handlers/itslearning-persons.event-handler.spec.ts
src/modules/itslearning/event-handlers/itslearning-persons.event-handler.ts
src/modules/itslearning/itslearning.service.ts
src/modules/itslearning/schemas.ts
src/modules/itslearning/types/role.enum.ts
src/modules/personenkontext/domain/personenkontexte-update.ts
src/shared/events/personenkontext-updated.event.ts

Creates or deletes memberships in itslearning, when personenkontexte change.

SPSH-827 Sync memberships with itslearning

---

migrations/.snapshot-dbildungs-iam-server.json
migrations/Migration20240816120248.ts
seeding/dev/01/04_rolle.json
src/console/dbseed/domain/db-seed.service.ts
src/console/dbseed/file/rolle-file.ts
src/modules/person/api/personenuebersicht/dbiam-personuebersicht.controller.integration.spec.ts
src/modules/personenkontext/api/dbiam-personenkontext-workflow.controller.integration-spec.ts
src/modules/personenkontext/domain/person-administration.service.ts
src/modules/personenkontext/domain/personenkontext-workflow.ts
src/modules/personenkontext/persistence/dbiam-personenkontext.repo.integration-spec.ts
src/modules/rolle/api/rolle.controller.ts
src/modules/rolle/domain/rolle.factory.ts
src/modules/rolle/domain/rolle.spec.ts
src/modules/rolle/domain/rolle.ts
src/modules/rolle/entity/rolle.entity.ts
src/modules/rolle/repo/rolle.repo.spec.ts
src/modules/rolle/repo/rolle.repo.ts

Hide migration rolle by adding the property "istTechnisch" to all rollen.

SPSH-953 Hide migration rolle and start work on technical rollen

---

charts/dbildungs-iam-server/templates/_dbildungs-iam-server-envs.tpl
charts/dbildungs-iam-server/templates/secret.yaml
charts/dbildungs-iam-server/values.yaml

SPSH-996 Add variable to helm template

---

src/modules/authentication/passport/oidc.strategy.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-990

Removed ACR requirement

---

test/utils/ldap-test.module.ts

While the previous port is available on the Devcluster, for infra, staging and prod only the ldaps port is open. So i would like to change the Port. Db Seeding init COntainer says that "LDAP: Successfully connected"

test ldap test module with port 636

---

seeding/dev/01/05_personenkontext.json

https://ticketsystem.dbildungscloud.de/browse/SPSH-1022

Entferne Zurodnung von Lehrer zu Klasse im Seeding

---

src/modules/person/api/person.controller.ts
src/modules/personenkontext/api/personenkontext.controller.ts

SPSH-1073 fix API generator

---

src/modules/organisation/persistence/organisation.repository.integration-spec.ts
src/modules/organisation/persistence/organisation.repository.ts

SPSH-1140 always return orgas queried by ID

---

src/core/ldap/domain/ldap-client.service.spec.ts
src/core/ldap/domain/ldap-client.service.ts
src/core/ldap/ldap-instance-config.ts
src/shared/config/ldap.config.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-1333

Enabled override of email-domains via config

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
charts/dbildungs-iam-server/values.yaml

Improve Tests Timeout and get rid of kics scan error

DBP-0000-Pipeline-imrpvements

---

src/modules/organisation/api/organisation.controller.ts
src/modules/person/api/person.controller.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-1519

SPSH-1519 Remove & Comment Out StepUpGuard For Migration EPs

---

src/modules/organisation/api/organisation.controller.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-1560

Use StepUp Guard Again After Migration

---

charts/dbildungs-iam-server/templates/backend-ingress.yaml
charts/dbildungs-iam-server/templates/configmap.yaml

DBP-1147-ingress-https-release

---

charts/dbildungs-iam-server/templates/backend-ingress2nd.yaml
charts/dbildungs-iam-server/values.yaml

Add secondary ingress if enabled

added 2nd ingress

---

charts/dbildungs-iam-server/templates/pdb.yaml
charts/dbildungs-iam-server/values.yaml
src/modules/organisation/api/organisation.controller.ts

Dbp 1156 create pod disruption budget for spsh applications

---

src/modules/itslearning/event-handlers/itslearning-persons.event-handler.spec.ts
src/modules/itslearning/event-handlers/itslearning-persons.event-handler.ts
src/shared/events/personenkontext-event.types.ts
src/shared/events/personenkontext-updated.event.ts

SPSH-1582 HOTFIX: Send Personenkontexte to itslearning, if the Klasse is at an itslearning Schule

---

migrations/.snapshot-dbildungs-iam-server.json
migrations/Migration20250107072430-S.ts
src/modules/personenkontext/persistence/personenkontext.entity.ts

Add new index for `rolle_id` and change indices for `person_id` and `organisation_id` to `HASH`

SPSH-1667 Add/change indices for personenkontexte

---

src/modules/authentication/domain/person-permissions.spec.ts
src/modules/authentication/domain/person-permissions.ts
src/modules/person/api/person.controller.spec.ts
src/modules/person/api/person.controller.ts

SPSH-1628: 2FA for uem password for admins

---

src/core/ldap/domain/ldap-client.service.ts
src/core/ldap/domain/ldap-event-handler.spec.ts
src/core/ldap/domain/ldap-event-handler.ts
src/modules/email/domain/email-event-handler.spec.ts
src/modules/email/domain/email-event-handler.ts
src/modules/itslearning/event-handlers/itslearning-persons.event-handler.ts
src/modules/ox/domain/ox-event-handler.spec.ts
src/modules/ox/domain/ox-event-handler.ts

- enhance logging of operations which are triggered on PersonenkontextUpdatedEvents
- https://ticketsystem.dbildungscloud.de/browse/SPSH-1717

SPSH-1717: Enhanced logging regarding PersonenkontextUpdatedEvent

---

src/shared/error/global-exception.filter.spec.ts
src/shared/error/global-exception.filter.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-1705

SPSH-1705 Add Service Unavailable logging

---

charts/dbildungs-iam-server/templates/backend-deployment.yaml
charts/dbildungs-iam-server/templates/configmap.yaml
charts/dbildungs-iam-server/values.yaml

https://ticketsystem.dbildungscloud.de/browse/DBP-1204

Dbp 1204 merge to release 0102

---

charts/dbildungs-iam-server/templates/backend-service.yaml

We have seen that Updates lead to a Downtime when logged in. This is due to the service being updated and requiring the new version to be in the pod. But the new pod is just starting up and the old ones do not match the new version and get ignored. Therefore we need to remove the line that also filters for version.

DBP-1271-correct-kubernetes-service-for-no-downtime

---

charts/dbildungs-iam-server/kafka/scripts/create_topics.sh
compose.yaml
config/kafka-topics.txt
docs/kafka.md

SPSH-1726 Initialize kafka topics for local development

---

.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

was already approved in https://github.com/dBildungsplattform/dbildungs-iam-server/pull/907/files, but for some reason, the Playwright Tests did not run through no matter what i did, so i changed the branch. When this is merged the other PD can get closed: https://github.com/dBildungsplattform/dbildungs-iam-server/pull/907/files

DBP-1300 trivy addition

---

Dockerfile

Updated node version and server

---

src/modules/person/api/personinfo/person-info-kontext-organisation.response.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-2038

SPSH-2038 Fix Add Swagger Annotations

---

charts/dbildungs-iam-server/values.yaml

- remove cron-trigger-6
- https://ticketsystem.dbildungscloud.de/browse/SPSH-2085

SPSH-2085: Remove cron-trigger-6 (avoid automated deletion of non-enabled EmailAddresses)

---

charts/dbildungs-iam-server/templates/configmap.yaml
charts/dbildungs-iam-server/values.yaml
config/config.json
src/modules/ox/domain/ox.service.spec.ts
src/modules/ox/domain/ox.service.ts
src/shared/config/config.env.ts
src/shared/config/ox.config.ts
test/config.test.json

SPSH-2105 Add retry to OX (Cherry Pick from Release 1.6.1)

---

src/modules/ox/domain/ox-event-handler.spec.ts
src/modules/ox/domain/ox-event-handler.ts

SPSH-2097: More logging in OxEventHandler

---

src/modules/personenkontext/api/dbiam-personenkontext-workflow.controller.spec.ts
src/modules/personenkontext/api/dbiam-personenkontext-workflow.controller.ts
src/modules/personenkontext/api/param/dbiam-find-personenkontextworkflow-body.params.ts
src/modules/personenkontext/domain/personenkontext-creation.service.ts
src/modules/personenkontext/domain/personenkontext-workflow.spec.ts
src/modules/personenkontext/domain/personenkontext-workflow.ts
src/modules/personenkontext/domain/personenkontext.enums.ts

- added enum that describes  `operationContext` for `personenkontext-workflow`
- added query-param `operationContext` to `personenkontext-workflow`
- `checkPermissions` respects new parameter and sets `canCommit` correctly

SPSH-2189: OperationContext for PersonenkontextWorkflow

---

src/modules/personenkontext/api/dbiam-personenkontext-workflow.controller.ts
src/modules/personenkontext/api/param/dbiam-find-personenkontextworkflow-body.params.ts
src/modules/personenkontext/domain/personenkontext-creation.service.ts
src/modules/personenkontext/domain/personenkontext-workflow.factory.ts
src/modules/personenkontext/domain/personenkontext-workflow.spec.ts
src/modules/personenkontext/domain/personenkontext-workflow.ts

SPSH-1865 Personenkontexte Workflow Changes

---

src/core/ldap/domain/ldap-client.service.spec.ts
src/core/ldap/domain/ldap-client.service.ts

https://ticketsystem.dbildungscloud.de/browse/SPSH-2323

SPSH-2323 Add Logging To executeWithRetry in ldapClientService

---

charts/dbildungs-iam-server/cron/scripts/get_access_token.sh
charts/dbildungs-iam-server/values.yaml

SPSH-2445 Fix cronjobs

---

migrations/Migration20250806103000-D.ts
seeding/dev/01/03_service-provider.json

SPSH-2343-2: correct merkmale for email-sps

---

.github/workflows/chart-release-manual.yml
.github/workflows/create-release.yml
.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml

DBP-1657-Update Sonarqube GHA to 5.3.1 

---

charts/dbildungs-iam-server/values.yaml

OPS-9667 service monitor interval
